"""public site with sms alerts

Revision ID: 6c5268de09c3
Revises: 
Create Date: 2026-07-21 23:12:07.543832
"""
from alembic import op
import sqlalchemy as sa


revision = '6c5268de09c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('payout_low', sa.Float(), nullable=True),
    sa.Column('payout_high', sa.Float(), nullable=True),
    sa.Column('total_fund', sa.Float(), nullable=True),
    sa.Column('payout_note', sa.String(length=300), nullable=True),
    sa.Column('claim_url', sa.String(length=600), nullable=True),
    sa.Column('source_url', sa.String(length=600), nullable=False),
    sa.Column('administrator', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('proof_required', sa.Boolean(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('announced_on', sa.Date(), nullable=True),
    sa.Column('claim_deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_key', name='uq_source_key')
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_announced_on'), ['announced_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_claim_deadline'), ['claim_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_needs_review'), ['needs_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_status'), ['status'], unique=False)

    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('found', sa.Integer(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_runs_source'), ['source'], unique=False)

    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('confirm_code', sa.String(length=8), nullable=True),
    sa.Column('confirm_sent_at', sa.DateTime(), nullable=True),
    sa.Column('confirm_attempts', sa.Integer(), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('min_payout', sa.Float(), nullable=True),
    sa.Column('claim_required_only', sa.Boolean(), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=True),
    sa.Column('opted_out_at', sa.DateTime(), nullable=True),
    sa.Column('consent_ip', sa.String(length=64), nullable=True),
    sa.Column('consent_at', sa.DateTime(), nullable=True),
    sa.Column('sends_today', sa.Integer(), nullable=True),
    sa.Column('sends_day', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscribers_opted_out'), ['opted_out'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscribers_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_subscribers_verified'), ['verified'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_notified'), ['notified'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_program_id'), ['program_id'], unique=False)

    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'event_id', 'channel', name='uq_delivery')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_subscriber_id'), ['subscriber_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_subscriber_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_event_id'))

    op.drop_table('deliveries')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_program_id'))
        batch_op.drop_index(batch_op.f('ix_events_notified'))
        batch_op.drop_index(batch_op.f('ix_events_kind'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))

    op.drop_table('events')
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_verified'))
        batch_op.drop_index(batch_op.f('ix_subscribers_phone'))
        batch_op.drop_index(batch_op.f('ix_subscribers_opted_out'))

    op.drop_table('subscribers')
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_runs_source'))

    op.drop_table('scrape_runs')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_status'))
        batch_op.drop_index(batch_op.f('ix_programs_source'))
        batch_op.drop_index(batch_op.f('ix_programs_slug'))
        batch_op.drop_index(batch_op.f('ix_programs_published'))
        batch_op.drop_index(batch_op.f('ix_programs_needs_review'))
        batch_op.drop_index(batch_op.f('ix_programs_content_hash'))
        batch_op.drop_index(batch_op.f('ix_programs_claim_deadline'))
        batch_op.drop_index(batch_op.f('ix_programs_category'))
        batch_op.drop_index(batch_op.f('ix_programs_announced_on'))

    op.drop_table('programs')
    # ### end Alembic commands ###
