"""add follows and expected_open

Revision ID: 974bebfd01fc
Revises: 6c5268de09c3
Create Date: 2026-07-22 13:10:54.900248
"""
from alembic import op
import sqlalchemy as sa


revision = '974bebfd01fc'
down_revision = '6c5268de09c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_open', sa.String(length=120), nullable=True))

    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follows', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_column('follows')

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('expected_open')

    # ### end Alembic commands ###
