"""add pro subscription fields

Revision ID: 9821c1c856b3
Revises: 974bebfd01fc
Create Date: 2026-07-22 18:35:21.374390
"""
from alembic import op
import sqlalchemy as sa


revision = '9821c1c856b3'
down_revision = '974bebfd01fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pro', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pro_since', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pro_until', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_subscribers_is_pro'), ['is_pro'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_is_pro'))
        batch_op.drop_column('pro_until')
        batch_op.drop_column('pro_since')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('is_pro')

    # ### end Alembic commands ###
