"""add last_digest_at

Revision ID: fa0816f11360
Revises: 9821c1c856b3
Create Date: 2026-07-22 23:47:48.635957
"""
from alembic import op
import sqlalchemy as sa


revision = 'fa0816f11360'
down_revision = '9821c1c856b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_digest_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_column('last_digest_at')

    # ### end Alembic commands ###
